### PR TITLE
Interventions

### PR DESCRIPTION
**Pull request by tschwedes**

### CODE REVIEW

**Comment by tcbegley** [comment]
I'm just working on tidying up the adversarial examples, then I can take a look at this and take advantage of some of Gergely's recent changes.

**Comment by tcbegley** [comment]
Commit history got a bit messy, think it's all good now

**Comment by tcbegley** [comment]
Ok, this is ready to go now

**Comment by imrehg** [comment]
Checking this out.

**Comment by tcbegley** [comment]
Good riddance

**Pull request merged**
