### PR TITLE
add notebook linting check

### PR DESCRIPTION
**Pull request by imrehg**
Connects to #40

### CODE REVIEW

**Review by tcbegley — APPROVED** [review]
awesome 🚀

**Comment by imrehg** [comment]
@tcbegley I've added Flake8 as well, and it found some things to fix on the notebooks (also highlights unused imports ;). Will not fix those up in this PR, but should inform subsequent PRs which work on the notebooks.

**Comment by tcbegley** [comment]
Wow, why did it never occur to me that `flake8-nb` might be a thing 🤯 

That's great! I'll happily submit a PR to tidy up failing checks once this is merged.

**Comment by imrehg** [comment]
Yeah, I went looking after your `black-nb` suggestion, I never thought of _that_. :D

**Comment by imrehg** [comment]
Got to the point of workflow is breaking in a known way, ready to merge for now :)

**Pull request merged**
